config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books
root 'root#top'
delete '/books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
		@book = Book.new
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
		  flash[:notice] = "Book was successfully updated."
		  redirect_to book_path(@book)
		else
			render("books/new")
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		  flash[:notice] = "Book was successfully updated."
		  redirect_to book_path(@book)
		else
			render("books/new")
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
   
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title, class: "book_title" %>

<h4>Body</h4>
<%= f.text_area :body, class: "book_body" %>
<%= f.submit "Update book" %>

<% end %>

<%= link_to "Show", book_path(@book), class: "show_#{@book.id}" %> | <%= link_to "Back", books_path, class: "back" %>

app/views/books/index.html.erb
<h2>Books</h2>

<table>
	<thead>
		<tr>
		<th>Title</th>
		<th>Body</th>
		</tr>
	</thead>
	<tbody>
	<% @books.each do |book| %>
	<tr>
		<td><%= book.title %></td>
		<td><%= book.body %></td>
		<td>
			<%= link_to "Show", book_path(book), class: "show_#{book.id}" %>
		</td>
		<td>
			<%= link_to "Edit", edit_book_path(book), class: "edit_#{book.id}" %>
		</td>
		<td>
			<%= link_to "Destroy", destroy_book_path(book), class: "destroy_#{book.id}", method: :delete, data: { confirm: '削除しますか'} %>
		</td>
	</tr>
	<% end %>
	</tbody>
</table>

<h3>New book</h3>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title, class: "book_title" %>
<h4>Body</h4>
<%= f.text_area :body, class: "book_body" %>

<%= f.submit "Create book" %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<h2>Title:</h2>
<p><%= @book.title %></p>

<h2>Body:</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book), class: "edit_#{@book.id}" %> | <%= link_to "Back", books_path, class: "back" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br><br>
印象を共有し交換することができます</p>

<%= link_to "Start", books_path %>